CREATE DATABASE hospital_db_atv3;
USE  hospital_db_atv3;

CREATE TABLE pacientes
(id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(45) NOT NULL,
datanasc DATE NOT NULL,
endereco VARCHAR(45) NOT NULL,
telefone VARCHAR (45) NOT NULL,
email VARCHAR(45) NOT NULL,
CPF VARCHAR(45) NOT NULL UNIQUE,
RG VARCHAR(45) NOT NULL UNIQUE);

CREATE TABLE medicos
(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR (45) NOT NULL,
datadenascimento DATE NOT NULL,
cpf VARCHAR(45) NOT NULL UNIQUE,
crm VARCHAR(45) NOT NULL,
uf_crm VARCHAR(20)  NOT NULL,
telefoneMedico VARCHAR (45) NOT NULL,
endereco VARCHAR(45) NOT NULL);

CREATE TABLE especialidades
(id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
descricao_especialidade VARCHAR(45) NOT NULL);

CREATE TABLE receitas
(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
medicamentos_qnt_instrucoes text default null);

CREATE TABLE consultas
(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
dataHora DATETIME NOT NULL,
valorConsulta DECIMAL(6,2) NOT NULL);

CREATE TABLE convenios
(id INT NOT NULL  AUTO_INCREMENT PRIMARY KEY,
nomeDoConvenio VARCHAR (45) NOT NULL,
cnpj VARCHAR(45) NOT NULL UNIQUE,
tempoCarencia VARCHAR(45) NOT NULL,
numConvenio INT NOT NULL);

CREATE TABLE medico_especialidades
(idmedico_especialidade INT NOT NULL AUTO_INCREMENT PRIMARY KEY);

CREATE TABLE internacao
(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
data_entrada DATETIME NOT NULL,
data_prev_alta date default null,
data_alta DATETIME NOT NULL,
procedimento VARCHAR(75) NOT NULL);

CREATE TABLE quartos
(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
numero_quarto int default null);

CREATE TABLE tipo_quarto
(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
descricaoquarto VARCHAR (150) DEFAULT NULL,
valor_diaria DECIMAL (6,2) DEFAULT  NULL);

CREATE TABLE enfermeiro
(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(45) NOT NULL,
cpf VARCHAR(30) NOT NULL UNIQUE,
cre VARCHAR(20) NOT NULL);

CREATE TABLE internacao_enfermeiro
(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY);